# Generated by Django 5.0.6 on 2024-05-30 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                (
                    "request_approver",
                    models.ForeignKey(
                        limit_choices_to={"role": "AP"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request_placer",
                    models.ForeignKey(
                        limit_choices_to={"role": "CO"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placed_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
